### ISSUE TITLE
Integrate the mocked JS parser into the tools

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#103]
We should integrate the mocked JS parser into the generator and templates to start using it and see if the API should be re-evaluated.

- [x] Integrate with the generator
   - https://github.com/asyncapi/generator/pull/551
- [x] Integrate with the template ts-nats-template - partly, nothing specific
- [x] Integrate with the template java-spring - partly, nothing specific
- [x] Integrate with the template nodejs-ws
    - https://github.com/asyncapi/nodejs-ws-template/pull/65
- [x] Integrate with the template markdown
    - https://github.com/smoya/markdown-template/tree/feature/intent_api

**Comment by jonaslagoni** [comment]
@smoya I think we can close this issue now right? 🤔

**Comment by smoya** [comment]
Yup @jonaslagoni
