### ISSUE TITLE
Data models generation

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/shape-up-process#21]
<h2>On This Page</h2>

- [Summary](#summary)
  - [Problem Overview](#problem-overview)
  - [Solution Overview](#solution-overview)
  - [Positive Side-Effects](#positive-side-effects)
- [Problem Details](#problem-details)
  - [Generating strong-typed data models is a rather complex task](#generating-strong-typed-data-models-is-a-rather-complex-task)
  - [Complex and unmaintainable template files](#complex-and-unmaintainable-template-files)
  - [Creating and maintaining data model generators for many languages is an arduous task](#creating-and-maintaining-data-model-generators-for-many-languages-is-an-arduous-task)
- [Solution guidelines](#solution-guidelines)
  - [My proposed "solution"](#my-proposed-solution)
  - [These examples are suggestions](#these-examples-are-suggestions)
- [Boundaries](#boundaries)
    - [Don’t do](#dont-do)
    - [Watch out for](#watch-out-for)
- [Long-Term Vision](#long-term-vision)

### Problem Overview

1. Generating strong-typed data models is a rather complex task.
1. Complex and unmaintainable template files.
1. Creating and maintaining data model generators for many languages is an arduous task.

### Solution Overview

1. Design an SDK to generate strong-typed data models from AsyncAPI / JSON Schema.
1. The SDK must be suitable for Nunjucks as well as for React.
1. The SDK must allow for the extensibility of existing data model definitions.

### Positive Side-Effects

1. Less code fragmentation and duplication across templates. 

### Generating strong-typed data models is a rather complex task

As of today, generating data models is a purely manual task that every template developer should take care of. There are lots of things to take into account when creating a generic solution even when it's for a specific programming language. To name a few:

* Map data types from JSON Schema to the selected programming language.
* Make sure variable names are valid and conforming to the standards of the language.
* Branching logic, i.e., creating some lines of code depending on the constraints of a property. For instance, validating that a number is between the specified minimum and maximum values before it's assigned on a setter method.

### Complex and unmaintainable template files

The complexity described above also creates some bad side-effects, like the [difficulty to read and maintain a data model template](https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/partials/java-class). Using React may improve the readability but that will leave out the developers who prefer Nunjucks.

### Creating and maintaining data model generators for many languages is an arduous task

If creating and maintaining a data model generator for a single programming language is hard, imagine doing the same for many programming languages. And keeping them updated and in-sync in terms of features is another challenge. E.g., making sure all of them support annotations, different visibility levels, etc.

## Solution guidelines

Since we want to solve these problems for Nunjucks and React templates, the solution goes through an SDK that both frameworks would use. It may be used behind the scenes by providing filters in Nunjucks and components in React. In any case, there must be a framework-agnostic solution.

**For now, the solution is to invest some time in thinking and designing that SDK.** Let me outline a few things I found out during my research:

* It must be framework-agnostic. We'll use it ourselves but, in practice, anyone should be able to use it in their tools.
* It is not enough to generate code. We need to somehow understand how this code is composed, e.g., where `import` or `require` statements start and end, what's a method definition, what's a class attribute, how annotations work, and more.
* We should be able to "alter" an existing template. E.g., add custom annotations, custom methods, etc.

### My proposed "solution"

Let's start with an example. Assuming we have a schema like the following:

```js
{
  type: 'object',
  properties: {
    displayName: {
      type: 'string'
    },
    email: {
      type: 'string',
      format: 'email'
    },
    createdAt: {
      type: 'string',
      format: 'date-time'
    }
  }
}
```

...and this code using the SDK:

```js
const { generateModelFor, Constants, buildMethod, buildGetters, buildSetters, typeNameFor, varNameFor, annotate } = require('@asyncapi/generator-sdk')
const schema = new Schema(UserSignedUp)

return generateModelFor('java', schema, {
  package: 'com.asyncapi',
  dependencies: ['com.fasterxml.jackson.annotation.JsonFormat'],
  annotations: {
    properties: (property, propertyName) => {
      if (property.format() !== 'date-time') return property

      annotate(property, 'JsonFormat', [{
        shape: 'JsonFormat.Shape.STRING',
        pattern: '"dd-MM-yyyy hh:mm:ss"',
      }])
    },
    methods: (method) => {
      const { name, visibility, isStatic, returnType, arguments } = method
      annotate(method, 'SomeAnnotation', [{
        someAnnotationKey: '"someAnnotationValue"',
      }])
    }
  },
  methods: {
    hashCode: null, // Removes hashCode method from the generated result
    findEvenOdd: buildMethod({
      name: 'findEvenOdd',
      visibility: Constants.Visibility.PUBLIC,
      static: true,
      returnType: 'String',
      parameters: [{
        name: 'num',
        type: 'int',
        // default: 0,
      }],
      body: '// method implementation here...'
    }),
    // getters
    ...buildGetters(schema),
    // setters
    ...buildSetters(schema),
  },
})
```

The following should be generated:

```java
package com.asyncapi;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.text.DateFormat;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserSignedUp {

  @JsonProperty("displayName")
  private String displayName;
  
  @JsonProperty("email")
  private String email;

  @JsonProperty("createdAt")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy hh:mm:ss")
  private Date createdAt;

  constructor (String displayName, String email, Date createdAt) {
    this.displayName = displayName;
    this.email = email;
    this.createdAt = createdAt;
  }

  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public String getDisplayName () {
    return displayName;
  }
  
  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public String getEmail () {
    return email;
  }
  
  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public Date getCreatedAt () {
    return createdAt;
  }

  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public void setDisplayName (String newDisplayName) {
    displayName = newDisplayName;
  }
  
  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public void setEmail (String newEmail) {
    email = newEmail;
  }
  
  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public void setCreatedAt (String newCreatedAt) {
    return DateFormat.parse(newCreatedAt);
  }

  @SomeAnnotation(SomeAnnotationKey = "SomeAnnotationValue")
  public static void findEvenOdd (int num) {
    // method implementation here...  
  }
}
```

Afterward, this SDK can power Nunjucks filters and React components. See the following React example:

```jsx
import { Model, Constants } from 'generator-react-sdk'
const schema = new Schema(UserSignedUp)

return (
  <Model
    language="java"
    schema={schema}
    annotateProperties={prop => {
      if (prop.format() !== 'date-time') return prop

      return annotate(prop, 'JsonFormat', [{
        shape: 'JsonFormat.Shape.STRING',
        pattern: 'dd-MM-yyyy hh:mm:ss',
      }])
    }}
    annotateMethods={method => {
      const { name, visibility, isStatic, returnType, arguments } = method
      annotate(method, 'SomeAnnotation', [{
        someAnnotationKey: '"someAnnotationValue"',
      }])
    }}
    methods={{
      hashCode: null, // Removes hashCode method from the generated result
      findEvenOdd: {
        visibility: Constants.Visibility.PUBLIC,
        static: true,
        returnType: 'String',
        parameters: [{
          name: 'num',
          type: 'int',
          // default: 0,
        }],
        body: '// method implementation here...'
      }
    }}
    buildGetters={true}
    buildSetters={true}
  />
)
```

### These examples are suggestions

This pitch/bet is actually about ideating and designing the SDK (excluding the React one). Let's make sure it works with any kind of programming language (object-oriented, functional, etc.)

A good starting list of languages to test against are:

* Java
* JavaScript / Node.js
* Python
* C#
* [GraphQL data type](https://graphql.org/learn/schema/)
* C++
* [Haskell](http://learnyouahaskell.com/making-our-own-types-and-typeclasses)

And a good starting list of artifacts that programming languages may offer:

* Packages
* Imports
* Interfaces
* Classes
  * Inheritance (may be possible to inherit from multiple classes)
* Attributes
* Methods
  * Getters
  * Setters
* Annotations
* Decorators
* Visibility
  * Public
  * Private
  * Protected
  * There may be others...
* Basic Types
* Functions
* Parameters (functions, methods, etc.)

#### Don’t do

* **Please don't write a single line of code for the SDK yet.** It's ok to have proofs of concepts in your machine if that helps you. Remember, the goal is to get a basement from where we'll build a great SDK in the future.
* Don't go too far trying to define all the possibilities a programming language can offer. Let's stick to the API surface. For instance, we're not interested in defining the inners of the body of a function. A simple string would suffice.

#### Watch out for

* Java Annotations and Python Decorators are not the same: https://stackoverflow.com/questions/15347136/is-a-python-decorator-the-same-as-java-annotation-or-java-with-aspects

## Long-Term Vision

In the short term, the idea behind this SDK is to power the Generator templates, making it super easy to create new ones. However, long-term applications are also interesting. A declarative way of generating code will also help us with:

* **SDK generation.** We may end up providing an AsyncAPI-first SDK (not to confuse with the Generator SDK) for multiple programming languages.
* **Parser generation.** Since we're able to generate code in any language, it would be easier for us to automatically generate some parts of the AsyncAPI parsers that we'll write for other languages.

That said, focus on the short-term goals for now. We don't want to end up creating a super generic solution.

Happy ~coding~ designing! :blush:

**Comment by jonaslagoni** [comment]
Just to mention this as a possible solution, would it really make sense to reinvent the wheel? [QuickType ](https://github.com/quicktype/quicktype) is already open source which does exactly this with the same license as us.

Quick intro to QuickType, it generates [strongly-typed models for multiple languages](https://github.com/quicktype/quicktype#target-languages) and serializers from JSON file or url, JSON Schema, TypeScript or GraphQL queries. Already have an easy wrapper in a [template filter](https://github.com/jonaslagoni/asyncapi-quicktype-filter) which are used in [quicktype template](https://github.com/jonaslagoni/asyncapi-quicktype-template). 

Choosing an existing open source solution slingshots us quite far in terms of starting point where only a wrapper would be sufficient. 

Some downsides of quicktype I see (as of this writing)

- Only 2 maintainers atm
    - Unless we pledge to help?
- No real documentation on how to start a new language, as well as the magic behind it.
- There is a problem with how the current AsyncAPI parser works and what QuickType expects as input which limits us somewhat from using it atm - see https://github.com/jonaslagoni/asyncapi-quicktype-filter/issues/15 
- I didn't find a good way to find the possible options for a language if you want to integrate QuickType in your code.


Reading materiale for further understanding:
- Main [github](https://github.com/quicktype/quicktype) readme
- Their [blog](https://blog.quicktype.io/) have some good write-ups 
- [Description on the setup and packages](https://github.com/quicktype/quicktype/blob/master/PACKAGES.md)

**Comment by fmvilas** [comment]
Yeah, Quicktype was my first choice when I started investigating it. I wanted us to have something more customizable. For instance, you can add custom annotations, custom methods, remove methods from the default output, etc. This pitch is about figuring out how we're going to do this so if you guys decide Quicktype is the way to go (even if it's behind the scenes), I'm all for it.

Main reasons I've hesitant to mention Quicktype here:
1. Only 2 maintainers. I offered help but got no response. Tried to reach out on Twitter private messages and email but got no response 🤷‍♂️ On issues, they're not replying or replying super late so I'm not sure it's a good idea to rely on a library like this. It hurts me to say it because the result is neat.
1. We need more levels of customization (as noted above). It's true we can ship something faster with Quicktype but we're not in a rush, right? :) Whatever we decide, let's make sure is for the long term because once we have lots of templates using our SDK it will not be easy to change.

Let me remember this pitch is exactly about figuring out the best solution, not implementing it. What I wrote here are just suggestions based on my findings while investigating how to do it. If we select this pitch for the cycle, the expected output is a thoroughly documented solution and zero code.

**Comment by fmvilas** [comment]
Just recorded a video explaining the concept/idea I had in mind. It is not mutually exclusive with Quicktype: https://www.youtube.com/watch?v=lAx0ZzmWUVI

**Comment by derberg** [comment]
I also have mixed feelings with quicktype. I was fan of it, especially when I [found out](https://github.com/asyncapi/generator/issues/216#issuecomment-638964451) the generated output can be modified but yeah, recently to me quicktype situation = nunjucks, so at the end a tool that has its limits, you cannot overcome fast or at all. I hate reinventing the wheel too though.

Regarding research, I think when working on design, you need to probably take into account how indentation will be handled during generation, for languages like Python. I know that Michael had to have special filters for nunjucks to handle those properly, pretty cumbersome. 

Also, after watchin the video, looks like you have to look on syntax of every possible language, or at least those that are already supported by quicktype. Good luck 🤞

**Comment by magicmatatjahu** [comment]
My few words:
- `sdk` should be written in the typed language - yes, lovelly TS. I know that some people when see `: {type}` signature get heart attack, but it gives feature that you can infer types from given arguments to functions, something like (it's only an idea):

```ts
return generateModelFor('java', schema, { ...{some object} });
```

and in this example you infer `java` name and then `{some object}` must includes only proper for Java properties. So for java you could use `annotations` but for other language like `typescript` you will give syntax error, than `{some object} is not a valid type`, when you use `annotations` field. I can describe it better if someone doesn't understand.

- we should check tools like `swagger-codegen`. As I know it is written in Java, but maybe we found something interesting in implementation, how these guys handle common problems like interface for other (custom) languages/frameworks.

- angular has something called [`schematics`](https://angular.io/guide/schematics) . It is a templates to generate common classes/structure for angular application. Is has very interesting think like updating class for given type (when angular has breaking changes in core - I mean breaking changes in typings), but I don't know what it exactly works under the hood. I only know that creating single schematics has a lot of boilerplate -> check this https://github.com/angular/schematics-angular-builds/tree/master/guard For single class you have to create 6 files (with dir) 😄

- I didn't use QuickTypes so I don't feel very confident writing about it, but we can check some solutions from their code (if we go to own solution).

- rather than thinking about AsyncAPI schema, we should think only about handling JSONSchema. If sdk will work for pure JSONSchema, then it should also works for AsyncAPI.

**Comment by jonaslagoni** [comment]
Think I need a more detailed explanation about what you mean by the first suggestion @magicmatatjahu :smile: 

>     * we should check tools like `swagger-codegen`. As I know it is written in Java, but maybe we'll find something interesting in implementation, how these guys handled common problems like interface for other (custom) languages/frameworks.

Might be a good idea yea, we just need to keep in mind there are no official maintained codegen from swagger, but we should look at the [OpenAPI-generator](https://github.com/OpenAPITools/openapi-generator). 

>     * rather than thinking about AsyncAPI schema, we should think only about handling JSONSchema. If sdk will work for pure JSONSchema, then it should also works for AsyncAPI.

After reading some more about what QuickType does under the hood, I had an idea or question. Would we really care what the input to the SDK is? :thinking: If we take any typed language wouldn't you be able to map types between each other "easily" i.e. you take any class from Java as input and feed it into the SDK which then are able to convert it to a type in any language of your choosing?

Whether the SDK reads a JSON Schema or a Java class it only matter of where you find the details for which the SDK needs to generate type files. Just like QuickType it takes inputs such as `JSON Schema, TypeScript or GraphQL queries` I think we should design the SDK to support this scenario.

**Comment by magicmatatjahu** [comment]
@jonaslagoni 

> Think I need a more detailed explanation about what you mean by the first suggestion @magicmatatjahu 😄

Let's image the situation, when user calls our function in this way:

```js
return generateModelFor('java', schema, { decorators: [...] } });
```

then TS should throws error, because in java you haven't decorators, but it's called `annotations`. In oppposite, when you will use function like:

```js
return generateModelFor('python', schema, { decorators: [...] } });
```

TS should passes your signature, because python has decorators (not annotations). It's called inferring types :)

> Might be a good idea yea, we just need to keep in mind there are no official maintained codegen from swagger, but we should look at the OpenAPI-generator.

As I see the `swagger-codegen` is the oldversion of `openapi-codegen` :) OpenAPI is a new name for swagger :) 

> After reading some more about what QuickType does under the hood, I had an idea or question. Would we really care what the input to the SDK is? 🤔 If we take any typed language wouldn't you be able to map types between each other "easily" i.e. you take any class from Java as input and feed it into the SDK which then are able to convert it to a type in any language of your choosing?
> 
> Whether the SDK reads a JSON Schema or a Java class it only matter of where you find the details for which the SDK needs to generate type files. Just like QuickType it takes inputs such as JSON Schema, TypeScript or GraphQL queries I think we should design the SDK to support this scenario.

Good point! But we should support only `static` data, I mean JSONSchema, GraphQL SDL. Handle, e.g. Java-Spring class with annotations and then converts it to Haskell (for example) types will be very hard.

**Comment by magicmatatjahu** [comment]
I have an idea to support React-JSX in data models generation and also in templating in way of some kind of AST (Abstract syntax tree). React-JSX is for creating tree for VirtualDOM, but it's very good to create static data like XML. Where am I going? For example, we have a Java class and using JSX we can create something like (this is only a idea):

```jsx
<Class name="SomeClass">
  <Property static private name="email" type="string" value="someEmail">
    <Annotation name="JsonProperty" value="email" />
  </Property>
  <Method public name="someMethod">
    <Argument type="string" name="displayName" />
    <Argument type="string" name="email" />
    <Body>
      return email == displayName;
    </Body>
  </Method>
</Class>
```

and then generator should return:

```java
class SomeClass {
  @JsonProperty("email")
  static private String email;

  public someMethod(String displayName, String email) {
    return email == displayName;
  }
}
```

Why this approach is very good? Because then you can override `Class ` `Method` `Argument` `Property` etc component to other language like python JS, C++. You can imagine that you wrote one definition for your template for Java, but developer can switch in generator cli from `java` to `python` and then `Class ` `Method` `Argument` `Property` component change behaviour and render something like:

```python
class SomeClass:
    email = "someEmail"

    def someMethod(self, displayName, email):
        return email == displayName
```

@jonaslagoni @fmvilas @derberg What do you think guys? Probably it won't be very generic and in some cases will breaks compability between languages, but simple JSON Schema types (string, arrays etc) for languages should be handled without huge boilerplate.

**Comment by derberg** [comment]
I'm not that deep in the topic so hard for me to share good opinion here. Tbh, I think this is such a complex topic that I would prefer to have components per language rather than one component for all, I'm just affraid of how complex will it be 😅

**Comment by fmvilas** [comment]
I think it's great but remember this is not just for React, it should also work for Nunjucks, that's why we have to go on a lower level. Eventually, what we achieve here, will be what back these components you defined. Feel free to open another issue in the Generator so we don't forget!

**Comment by derberg** [comment]
@fmvilas are you 100% sure we should take Nunjucks into consideration? shouldn't we consider that react and model generation is for 2.0 and that nunjucks will stay (or even not) in 2.0 just to give more time for migration

**Comment by fmvilas** [comment]
It's more of an exercise than wanting to keep Nunjucks around. If we make things framework-agnostic, it will be easy for us to get rid of React if that's needed. I don't think it will be but who knows 🤷‍♂️

**Comment by jonaslagoni** [comment]
> I think it's great but remember this is not just for React, it should also work for Nunjucks, that's why we have to go on a lower level. Eventually, what we achieve here, will be what back these components you defined.

**Comment by jonaslagoni** [comment]
Wups 😇 

> I think it's great but remember this is not just for React, it should also work for Nunjucks, that's why we have to go on a lower level. Eventually, what we achieve here, will be what back these components you defined.

I agree, the way I see it is that we are talking about 2 problems which needs to be figured out:

1. We need a renderer behind the scenes, and IMO @magicmatatjahu suggestion with React makes perfect sense to check out and see how it works. This would also benefit all our React template developers with reuseable helper components to template code in various languages because we build the stepping stones.
2. We need to figure out (based on the type renderer used behind the scenes) how this can be integrated into templates regardless of whether they use React or Nunjucks, or used in a library. This could be as you suggested with the "wrapper functions" with customization options. 

Further I think it would be a good idea to state the functional requirements for both the wrapper and underlying type renderer to get an idea of the range of the customization that should be possible. Do we care about non-functional requirements? 🤔 

What do you think? Am I missing something?

**Comment by jonaslagoni** [comment]
Closing this bet after a finished research cycle which mounted in the new pitch #43.
