### ISSUE TITLE
Create an <Indent> component

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/shape-up-process#27]
The template author should be able to use a component to indent text/code. We can call this component `<Indent>` or `<Text>`. It should take —at least— the following props:

* `size`: The size of the indentation.
* `type`: The type of indentation, either `spaces` or `tabs`.

### Hints

* Consider setting a default value for both `size` and `type`.
* Consider starting the docs, tests, and code of this component **before** any other tasks are finished, to increase work parallelization.

**Comment by magicmatatjahu** [comment]
Done by https://github.com/asyncapi/generator-react-sdk/commit/c884869529438216fa6b2235036c9520e3a9d225 commit
