### ISSUE TITLE
Create basic components

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/shape-up-process#28]
Offer the basic components a template author will need to create a template.

For more information, have a look at the issues of epic on Zenhub.

**Comment by jonaslagoni** [comment]
/progress 0 Started working on defining components and tests

**Comment by jonaslagoni** [comment]
/progress 25 Defined basic components and started created documentation for them. Tests are followed afterwards.

**Comment by jonaslagoni** [comment]
/progress 35 Basic components defined with a simple implementation as well as reusable indentation and newline functionality for prototyping (needs to be revisited since it seems like a mess we maybe can avoid).

**Comment by jonaslagoni** [comment]
/progress 60 Basic components defined with tests, still need to adapt with custom reconciler. SDK library created with docs.

**Comment by jonaslagoni** [comment]
/progress 90 Basic components seem to be steady now. Need a final review before finishing issue.

**Comment by magicmatatjahu** [comment]
/progress 100 Done by https://github.com/asyncapi/generator-react-sdk/commit/c884869529438216fa6b2235036c9520e3a9d225 commit
