### ISSUE TITLE
Create a custom React renderer

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/shape-up-process#29]
The custom React renderer should allow Generator to render templates for getting their content and metadata.

### Hints

* Have a look at React PDF renderer: https://github.com/diegomura/react-pdf/tree/master/src.
* This renderer should not write files but instead return the rendered content and some metadata information about the file (i.e., name and permissions). It's the responsibility of the Generator to write to the file system.

**Comment by magicmatatjahu** [comment]
/progress 25 I rewrote (for tests) with success, info and servers partials from markdown-template, but I want to take one day to improve rendering newlines. At the moment it isn't a good developer experience. However renderer works (also with nested custom component hierarchy)

**Comment by magicmatatjahu** [comment]
/progress 50 Renderer supports TS (I also helped Jonas to rewrite components to TS). Tests are also written. I refrained from fixing the new lines. I will deal with them at the end. Now I am starting integration with babel.

**Comment by magicmatatjahu** [comment]
/progress 60 Renderer is almost done. I started rewriting the entire markdown-template to see if it could handle complex cases and (eventually) fix bugs.

**Comment by magicmatatjahu** [comment]
/progress 75 Renderer should be stable. Task is waiting for the final integration in the generator.

**Comment by magicmatatjahu** [comment]
/progress 100 Done by https://github.com/asyncapi/generator-react-sdk/commit/c884869529438216fa6b2235036c9520e3a9d225 commit
