### ISSUE TITLE
Research other libraries

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#30]
Learn from what QuickType and OpenAPI generator has been through in regards to types and see if we can learn anything.

When the two research issues are done we share the findings.

Sub tasks:
* #32 
* #33 
* #34

**Comment by jonaslagoni** [comment]
/progress 5 Finished the research regarding QuickType.

**Comment by magicmatatjahu** [comment]
/progress 6 Start investigation on Angular Schematics and OpenAPI-codegen

**Comment by magicmatatjahu** [comment]
/progress 10 Finished the investigation on Angular Schematics. Comment is here https://github.com/asyncapi/shape-up-process/issues/34#issuecomment-745259865

**Comment by magicmatatjahu** [comment]
/progress 15 Finished the investigation of OpenAPI-generator. Comments is here https://github.com/asyncapi/shape-up-process/issues/33#issuecomment-745265653

**Comment by magicmatatjahu** [comment]
/progress 100 Investigation for tools is done.
