### ISSUE TITLE
Implement the transformation for JSON Schema to common model 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#45]
This issue is about implementing the code for transforming JSON Schema to our common model. Be aware that JSON Schema are provided in multiple versions. For now JSON schema draft 7 should be implemented.

This includes:
- Testing
- Documentation
- Implementation based on issue #53 and #51

**Comment by jonaslagoni** [comment]
/progress 5 started to look at the different transformations and simplification steps we need to perform for the common model.

**Comment by jonaslagoni** [comment]
/progress 10 have started to define how types are supposed to be simplified

**Comment by jonaslagoni** [comment]
/progress 15 roughly defined the how types are simplified, next is enumerators.

**Comment by jonaslagoni** [comment]
/progress 20 starting to push the limits of what JSON Schema should be used for in terms of it being a constraint language and us using it to determine type definitions. However `enum` simplification are done, next I gotta look at how we can simplify overall schemas. I suspect that we might need to add `allOf` keyword into `CommonSchema` since multiple types for arrays and objects are at the moment not supported.

**Comment by fmvilas** [comment]
@jonaslagoni IMHO `allOf` should not be present in CommonSchema. If I understood correctly, CommonSchema is a schema with all the common features from each programming language. Therefore, it should reflect what you can find in programming languages, not what you can find on the input.

As I said, that's just my opinion and I'm lacking a lot of the context so take it lightly.

**Comment by jonaslagoni** [comment]
/progress 55 Looks like our approach is correct, enum and type simplification are merged. Up next is properties and items.

**Comment by jonaslagoni** [comment]
/progress 70 Finished item simplification and waiting for review https://github.com/asyncapi/generator-model-sdk/pull/18

**Comment by jonaslagoni** [comment]
Progress 75 Item simplification done, next step is to review the entire input process with JSON schema and AsyncAPI to see if we are missing something in the simplification stage.

**Comment by jonaslagoni** [comment]
/progress 80 reviewed the processes and added simplified methods so we have single point of entry regardless of whether you want to generate something using a pure JSON schema or an entire AsyncAPI file.

**Comment by jonaslagoni** [comment]
/progress 90 JSON Schema now fully supports circular schemas, we now also has the information about `extend` to enable easy inheritance. Other then that all there is left for JSON Schema simplification is to give them correct identifiers/names for anonymous schemas.

**Comment by magicmatatjahu** [comment]
/progress 93 Open PR with simplification of schema's name

**Comment by jonaslagoni** [comment]
/progress 100 @magicmatatjahu PR with schema name inference is merged and the transformation of JSON Schemas are in a steady-state. Any further improvements will be added to the library as issues - https://github.com/asyncapi/generator-model-sdk/issues
