### ISSUE TITLE
Create the basic model for Java

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#47]
Create the basic model for Java.

This includes:
- Testing
- Documentation

If we'll go with React solution, here we have a needed components:

Must have to be implemented:
`<Package>`, `<Import>` (or `<Imports>`), `<Class>`, `<Constructor>`, `<Interface>`, `<Property>`, `<Method>`, `<Argument>` (as parameter in method/constructor), `<Enum>`, `<Annotation>`, `<Setter>` (or `<SetAccessor>`), `<Getter>` (or `<GetAccessor>`), `<Body>`. Getter and Setter could be include in `<Accessors>` component. String inside Method component could be treated as Body component.

Nice to have:
`<Lambda>`, [`<Record>`](http://tutorials.jenkov.com/java/record.html).

**Comment by magicmatatjahu** [comment]
/progress 20 Add basic class renderer for Java in this PR https://github.com/asyncapi/generator-model-sdk/pull/27

**Comment by magicmatatjahu** [comment]
/progress 50 Add class and enum (for string and integer type) renderer for Java types

**Comment by magicmatatjahu** [comment]
/progress 80 Integrate presets in basic Java models: class and enum.

**Comment by magicmatatjahu** [comment]
/progress 100 Implementation should be stable. Errors that occur during the integration will be reported to the `generator-model-sdk` repository.
