### ISSUE TITLE
Create the basic model for Javascript/Typescript

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#48]
Create the basic model for Javascript/Typescript.

This includes:
- Testing
- Documentation

If we'll go with React solution, here we have a needed components:

Must have to be implemented:
`<Module>` (for CommonJS), `<Import>` (or `<Imports>`), `<Class>`, `<Constructor>`, `<Method>`, `<Argument>` (as parameter in method/constructor), `<Setter>` (or `<SetAccessor>`), `<Getter>` (or `<GetAccessor>`), `<Function>`, `<Body>`, `<Property>`. Getter and Setter could be include in `<Accessors>` component. String inside Method component could be treated as Body component.

Nice to have:
`<Variable>` (as standalone variable), then `<Object>`, `<Array>` etc..., `<Lambda>`

For Typescript also:
`<Interface>`, `<Type>`, `<Decorator>`, `<Enum>`, `<Declare>`.

**Comment by magicmatatjahu** [comment]
/progress 5 Starting  implementation of basic model for Javascript/Typescript. I need wait to other task to go with it, so I will base impl. on mocks and then switch to processor flow.

**Comment by magicmatatjahu** [comment]
/progress 30 Create first draft for TS/JS generator in this Pr https://github.com/asyncapi/generator-model-sdk/pull/20

**Comment by magicmatatjahu** [comment]
/progress 50 Add generators for TS and JS types and make renderers for Enum, Interface, Class types.

**Comment by magicmatatjahu** [comment]
/progress 70 Generator and renderers for TS and JS types are almost done. I will add mix/extend, required etc. functionality when simplification process will be completed.

**Comment by magicmatatjahu** [comment]
/progress 80 Integrate presets in basic TS/JS models: class, interface, enum.

**Comment by magicmatatjahu** [comment]
/progress 100 Implementation should be stable. Errors that occur during the integration will be reported to the `generator-model-sdk` repository.
