### ISSUE TITLE
Integrate the Java model generation into a library

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/shape-up-process#49]
Once done we want to actually use the library in existing tools or templates. For Java we could integrate it into https://github.com/asyncapi/java-spring-template.

**Comment by magicmatatjahu** [comment]
/progress 5 Starting integration in https://github.com/asyncapi/java-spring-template

**Comment by magicmatatjahu** [comment]
/progress 60 Most have been integrated. I have to render by presets the nested enums, classes inside class etc ... is what we don't support in our library at the moment. PR is opened https://github.com/asyncapi/java-spring-template/pull/121

**Comment by magicmatatjahu** [comment]
/progress 85 PR is opened to review https://github.com/asyncapi/java-spring-template/pull/121

**Comment by magicmatatjahu** [comment]
/progress 90 PR is reviewed, some stuff has been transferred to `model-sdk` and is waiting for merge. Waiting for another review.
