### ISSUE TITLE
[Feature] Integrate context in React renderer

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/shape-up-process#54]
As in title: integrate context like in normal React in our React renderer. Idea is described [here](https://github.com/asyncapi/shape-up-process/issues/31#issuecomment-751710359).

Copied comment from above link:

## Context

If we go with React engine as a base solution for model generation, then we should also introduce context for React components. It should works similar to React-DOM context. Let's check the example:

```js
<NamespaceContext>
  <Namespace>
    <ClassContext>
      <Class>
        <PropertyContext>
          <Property />
        </PropertyContext>

        <MethodContext>
          <Method />
        </MethodContext>
      </Class>
    </ClassContext>
  </Namespace>
</NamespaceContext>
```

Then inside `Property` and `Method` components we can use contexts: `NamespaceContext`, `ClassContext`, `PropertyContext` (only Property can use it) and `MethodContext` (only Method can use it). In Class component we can use contexts: `NamespaceContext`, `ClassContext`. By this we lookup for contexts in parent components (not in children - it is not logical). 

Using context in component:

```js
import { useContext } from "@asyncapi/generator-react-sdk";

function Property({ ...props }) {
  // we can retrieve some data from ClassContext
  const { className } = useContext(ClassContext);
  // and also from NamespaceContext
  const { namespaceName } = useContext(NamespaceContext);
}
```

Context can store some data (because context can be written and used as normal JS class) in rendering time and then developer can change output based on stored data.

**Comment by magicmatatjahu** [comment]
/progress 40 I was able to create a context similar to React (in this PR https://github.com/asyncapi/generator-react-sdk/pull/19), but however I don't have any idea how to properly handle parallel case to speed up generation process. I'll postpone this task when we'll start implementation of model generation for Java/Typescript.

**Comment by fmvilas** [comment]
Hey folks! Any way I can help here? I see this scope has been stuck for 27 days already.

**Comment by magicmatatjahu** [comment]
/progress 100 It won't be integrated in `model-sdk`, maybe in future as feature, but not now.
