### ISSUE TITLE
Use parser-js in react-component

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/shape-up-process#85]
Internally in component we still use schema in inline way by `schema.info.contact.email`. We should start using `parser-js` and remove old typings inside component (or maybe leave?).

**Comment by fmvilas** [comment]
I'd be careful with this one. It seems to have a lot of potential for becoming a rabbit hole :smile:

Let's consider this one as a nice-to-have.

**Comment by magicmatatjahu** [comment]
@fmvilas We have covered at least 90% of our api in parser-js so I think that it shouldn't be rabbit hole, only one: new api for parser, but then we can switch to new one without problem (I think 😄).

**Comment by fmvilas** [comment]
I honestly can't foresee the implications of this Scope. I just know that it doesn't add anything valuable for the user. I know that making the code maintainable is a great thing but don't forget we're going to "redo" the whole React component in a future cycle, once we start implementing the UI library. So not sure it's worth the effort now.

**Comment by magicmatatjahu** [comment]
Yes, I agree with you but parser-js has some helper functions like `allSchemas` etc - this is one of requirements in bet description (`It has a section of messages and schemas but it only shows the ones under components.`) to handle rendering also the `anonymous-schemas` used as `oneOf` etc. I will check if here is a problem to move in everyplace to parser-js but in some we should - I don't want to duplicate code from parser-js.

**Comment by magicmatatjahu** [comment]
/progress 15 Info and Servers components are using `parser-js` api

**Comment by magicmatatjahu** [comment]
/progress 50 Info, Servers, Channels, Messages are using `parser-js` api. I left Schemas, because this part should be rewritten to meet the requirements of the task https://github.com/asyncapi/shape-up-process/issues/86

**Comment by magicmatatjahu** [comment]
/progress 55 Open PR - https://github.com/asyncapi/asyncapi-react/pull/264 Changes will be merged to `unify-component` branch.

**Comment by magicmatatjahu** [comment]
/progress 85 New component for Schema (in [PR](https://github.com/asyncapi/asyncapi-react/pull/269)) already uses `parser-js` API. After adapting components that use the old `Schema` component, the `beautify` stage will be removed and the task will be marked as completed.

**Comment by magicmatatjahu** [comment]
/progress 100 "New" component supports in every place parser API. PR with removing `beautifier` https://github.com/asyncapi/asyncapi-react/pull/285
