### ISSUE TITLE
[Nice-to-have] Use react-component in studio

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/shape-up-process#89]
Reference: https://github.com/asyncapi/studio/issues/10

Once https://github.com/asyncapi/shape-up-process/issues/85, https://github.com/asyncapi/shape-up-process/issues/86 and https://github.com/asyncapi/shape-up-process/issues/87 will done, we should remove the HTML template and start using the React component. This has many benefits. For instance, we can do everything on the client-side.

**Comment by fmvilas** [comment]
Just for the record: this is not a requirement. We can use Studio to test the "new" React component though. But full migration in Studio is not needed to complete this bet.

In other words, this is a nice-to-have.

**Comment by magicmatatjahu** [comment]
/progress 20 Create draft PR to show how we can integrate React component - https://github.com/asyncapi/studio/pull/17

I think that separate route `/parse` on backend should parse AsyncAPI spec from Editor and only in component we should consume parsed spec - parsing in backend is faster than in client and also client is much more light (in this situation, we don't need parser on client side).

**Comment by fmvilas** [comment]
I agree is better to parse on the backend but parsing in the frontend may be faster and in the end, our parser is meant to be browser compatible. Also, no backend round-trips mean less money and eventually easy to deploy on Netlify or similar.

**Comment by magicmatatjahu** [comment]
/progress 40 As suggested by Fran, I switched from server-side parsing to client-side parsing and I have this same problem like described [here](https://github.com/asyncapi/asyncapi-react/issues/197), so first I must fix problem in React component side to go further.

**Comment by magicmatatjahu** [comment]
/progress 75 Tested the `umd` bundle and it works. Waiting for https://github.com/asyncapi/shape-up-process/issues/105 and https://github.com/asyncapi/shape-up-process/issues/86 tasks to go forward.

**Comment by magicmatatjahu** [comment]
/progress 100 I have opened PR in studio https://github.com/asyncapi/studio/pull/17 I had bigger problems with bundles and html-template integration during the cycle. Although the task was nice-to-have, and I think that I did it partially. I will try to finish it in the coming days.
