### ISSUE TITLE
Implement a new JS Parser API

### ISSUE THREAD

**Issue by smoya** [asyncapi/shape-up-process#91]
Based on what is defined in https://github.com/asyncapi/shape-up-process/issues/90, implement a new API for https://github.com/asyncapi/parser-js.

We should make some decisions on the approach we want to take for:

- Integrating changes into master VS a new branch. 
  - Integrating changes may lead to the leak of bugs in case we release a new version prior to finish the new API. 
  - On the other hand, keeping all in a separated branch could end up being a pain when merging all back to the main branch.
- Do we wanna keep the old API methods available? 
  - Keep it for at least 1 more version but as deprecated? 
  - Do we wanna instead force users to reimplement their calls and use the new API (breaking change)?

The outcome of this issue should be:

- A new API implementation based on https://github.com/asyncapi/shape-up-process/issues/90, implement a new API for https://github.com/asyncapi/parser-js
- Public face documentation
- Tests

**Comment by jonaslagoni** [comment]
/progress 10 Implemented the first initial mock API

**Comment by smoya** [comment]
We are closing this scope as won't do by now. More details [here](https://github.com/asyncapi/shape-up-process/issues/82#issuecomment-817643767)
